version: '3'

tasks:
  setup:
    desc: Initialize project environment
    cmds:
      - echo "Setting up project environment..."

  check:
    desc: Run all validation checks
    cmds:
      - echo "Running validation checks..."

  fmt:
    desc: Format all code and configuration files
    cmds:
      - echo "Formatting files..."

  lint:
    desc: Run linters and static analysis
    cmds:
      - echo "Running linters..."

  docs:
    desc: Build project documentation
    cmds:
      - echo "Building documentation..."
